<a href="https://colab.research.google.com/github/MhdAftab/Start_new-2/blob/main/Numpy_27_7_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

##Comparing Time

In [ ]:
N = 100000000

In [ ]:
%%time
list_ = list(range(N))
for i in range(N):
  list_[i] = list_[i] * list_[i]

CPU times: user 32 s, sys: 2.19 s, total: 34.2 s
Wall time: 34.2 s


In [ ]:
%%time
list_ = list(range(N))
list_ = [item*item for item in list_]

CPU times: user 11.2 s, sys: 5.67 s, total: 16.9 s
Wall time: 16.9 s


In [ ]:
%%time
list_ = list(range(N))
list_ = map(lambda x : x*x, list_)

CPU times: user 2.49 s, sys: 1.9 s, total: 4.39 s
Wall time: 4.36 s


In [ ]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
  list_sum += item

CPU times: user 14.4 s, sys: 1.89 s, total: 16.3 s
Wall time: 16.2 s


In [ ]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 3.3 s, sys: 1.67 s, total: 4.97 s
Wall time: 4.93 s


In [ ]:
%%time
arr = np.arange(N) # arr of size n and every item is 0,1,2,3,4.......N
arr = arr * arr # elementwise multiplication (eg 0*0, 1*1, 2*2.....)

CPU times: user 478 ms, sys: 18.9 ms, total: 497 ms
Wall time: 513 ms


In [ ]:
%%time
arr = np.arange(N) 
arr_sum = np.sum(arr)

CPU times: user 295 ms, sys: 20.8 ms, total: 316 ms
Wall time: 319 ms


#Creating np array

In [ ]:
arr = np.arange(5)

In [ ]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
arr = np.array([1,2,3,4,5]) # Converting a list to np array
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
arr.dtype # data type of each element of np array with capacity (64 bytyes)

dtype('int64')

In [ ]:
arr.ndim # number of dimension of an array

1

In [ ]:
arr.shape # shape of an array

(5,)

In [ ]:
arr.size # total number of elements in numpy array

5

In [ ]:
arr.itemsize # number of bytes required to store a single item 

8

In [ ]:
arr = np.array([1.0,2,3,4,5]) # it will read as floating points as one of elements changes to float
print(arr, type(arr))

[1. 2. 3. 4. 5.] <class 'numpy.ndarray'>


In [ ]:
arr.dtype

dtype('float64')

2D np array

In [ ]:
arr2d = np.array([
                  [1,2,3],
                  [4,5,6]
])

In [ ]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d.size

6

3D np Array

In [ ]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10,11,12]
                  ]
])

In [ ]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d.size

12

In [ ]:
# array of all the values to be ones
np.ones((2,3,4)) # argument-> tuple of desried shape

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# array of all the values to be any scalar value
1234*np.ones((2,3,4)) # broadcast scalar value(1234) in the desired shape and then elementwise multilplication

array([[[1234., 1234., 1234., 1234.],
        [1234., 1234., 1234., 1234.],
        [1234., 1234., 1234., 1234.]],

       [[1234., 1234., 1234., 1234.],
        [1234., 1234., 1234., 1234.],
        [1234., 1234., 1234., 1234.]]])

In [ ]:
# array of all the values to be zeroes
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.random.randn(2, 3) #(arg=> shape of an array) generate series of 2*3 numbers randomly sampled from a normal dist.. with 0 mean and unit SD

array([[ 1.78668949, -0.63157103, -0.27832356],
       [-0.62465795,  0.42026742, -0.85215212]])

In [ ]:
np.random.rand(2, 3) #(arg=> shape of an array) random numbers uniformly sampled between 0 and 1 (each number equally likely)

array([[0.39554053, 0.55502816, 0.66871267],
       [0.54632947, 0.98919504, 0.91817617]])

In [ ]:
np.random.randint(0, 100, (2, 3)) #(arg=> min_lim, max_lim, shape of arr) random number between min_lim and max_lim with the given shape

array([[70, 14, 84],
       [48, 74, 71]])

In [ ]:
np.arange(7, 71, 5) # (arg=> min_lim, max_lim(exclusive), step_size) generate all numbers btw 7, 71 with diff 7(step_size) in btw 

array([ 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67])

In [ ]:
np.linspace(7, 70, 10) #(arg=> min_lim, max_lim, number of points) 10 points at linear distance between 7 and 70

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [ ]:
np.array([True, False, False, True])

array([ True, False, False,  True])

In [ ]:
str_arr = np.array(['1.2','2.3','4.5','9.8'])

In [ ]:
arr = np.array(str_arr, dtype='float') # converting string array to float type if possible

In [ ]:
arr

array([1.2, 2.3, 4.5, 9.8])

In [ ]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10,11,12]
                  ]
])

In [ ]:
arr3d[0,1,2]

6

In [ ]:
arr3d[1,0,2]

9

In [ ]:
arr3d[0,:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d[1,:,0:2]

array([[ 7,  8],
       [10, 11]])

In [ ]:
# fancy indexing => we want all the numbers that is divisible by 2 .. we can do this by iterating but we use numpy feature
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [ ]:
arr3d[arr3d % 2 == 0] # given a 1d array of all the numbers % 2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr_slice = arr3d[:,:,0:2]
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [ ]:
arr_slice[0,0,0] = 1729

In [ ]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [ ]:
arr3d # arr3d(original array also gets changed) .. shallow copy, only refrence is copied

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
arr_slice = np.copy(arr3d) # deep copy.. values get copied

In [ ]:
arr_slice[0,0,0] = 1

In [ ]:
arr_slice

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d # org arr not changed

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
arr = np.random.randint(0, 10, (5))

In [ ]:
arr

array([5, 7, 7, 3, 1])

In [ ]:
my_indices = [1,3,4]

In [ ]:
arr[my_indices] # treat elements of list(my_indices) as indices of array

array([7, 3, 1])

#Numpy Operations

In [ ]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [ ]:
arr1

array([[0.17867717, 0.94945474, 0.04107655, 0.9875363 ],
       [0.56199973, 0.17688714, 0.22048363, 0.57653855],
       [0.85156955, 0.79368835, 0.27388781, 0.41071886]])

In [ ]:
arr2

array([[0.03668468, 0.22417465, 0.00721436, 0.96278409],
       [0.3406023 , 0.96259724, 0.13667196, 0.01250904],
       [0.69545576, 0.69856851, 0.69489521, 0.04649735]])

In [ ]:
arr1 + arr2 # pointwise addition

array([[0.21536185, 1.17362939, 0.04829091, 1.9503204 ],
       [0.90260203, 1.13948438, 0.35715559, 0.58904759],
       [1.54702531, 1.49225686, 0.96878302, 0.45721621]])

In [ ]:
arr1 - arr2 # pointwise subtration

array([[ 0.14199248,  0.72528008,  0.03386218,  0.02475221],
       [ 0.22139743, -0.78571011,  0.08381167,  0.56402952],
       [ 0.15611379,  0.09511985, -0.4210074 ,  0.36422152]])

In [ ]:
arr1 * arr2 # pointwise multipliation

array([[6.55471536e-03, 2.12843687e-01, 2.96341055e-04, 9.50784247e-01],
       [1.91418403e-01, 1.70271070e-01, 3.01339297e-02, 7.21194173e-03],
       [5.92228947e-01, 5.54445687e-01, 1.90323330e-01, 1.90973371e-02]])

In [ ]:
arr1 / arr2 # pointwise division

array([[ 4.87062032,  4.23533489,  5.69371875,  1.02570899],
       [ 1.6500174 ,  0.18376028,  1.61323239, 46.08976563],
       [ 1.22447696,  1.13616395,  0.39414261,  8.83316792]])

In [ ]:
np.exp(arr1)

array([[1.19563469, 2.58430015, 1.04193186, 2.68461225],
       [1.75417687, 1.19349638, 1.24667952, 1.77986684],
       [2.34332193, 2.21153834, 1.31506726, 1.50790137]])

In [ ]:
np.log(arr1)

array([[-1.72217464, -0.05186742, -3.19231798, -0.01254202],
       [-0.57625391, -1.73224339, -1.51193182, -0.55071307],
       [-0.1606741 , -0.2310644 , -1.29503669, -0.88984633]])

In [ ]:
np.log(np.exp(arr1))

array([[0.17867717, 0.94945474, 0.04107655, 0.9875363 ],
       [0.56199973, 0.17688714, 0.22048363, 0.57653855],
       [0.85156955, 0.79368835, 0.27388781, 0.41071886]])

In [ ]:
arr_inv = 1 / arr1

In [ ]:
arr_inv

array([[ 5.59668602,  1.0532361 , 24.34479283,  1.012621  ],
       [ 1.77936029,  5.65332233,  4.5354841 ,  1.73448938],
       [ 1.1743022 ,  1.25994037,  3.65112995,  2.43475547]])

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr_inf = 1 / arr # wont throw 0 div error .. it gives output as infinity

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
arr_inf

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [ ]:
np.isinf(arr_inf[0, 0]) # function to check whether value at particular idx is infinity or not 

True

In [ ]:
np.isinf(arr_inf) # vectorized form of func

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

#Exercise on finding number of points outside n-dim sphere

In [ ]:
ndim = 2

In [ ]:
npoints = 1000000

In [ ]:
points = np.random.rand(npoints, ndim) # random array of size npoints*ndim

In [ ]:
dfo = np.zeros((npoints,1))
outside_points = 0

In [ ]:
# iteration is taking lot of time even if we are using numpy arr
%%time
for i in range(npoints):
  for j in range(ndim):
    dfo[i] += points[i,j] ** 2
  dfo[i] = np.sqrt(dfo[i])
  if dfo[i] > 1:
    outside_points += 1

CPU times: user 14.9 s, sys: 2.02 s, total: 16.9 s
Wall time: 14.8 s


In [ ]:
print("Fraction of points outside: ", outside_points/npoints)

Fraction of points outside:  0.214433


In [ ]:
%%time
sqr_points = points * points
dfo = np.sqrt(np.sum(sqr_points, axis = 1))
outside_points = np.sum(dfo > 1)

CPU times: user 38.7 ms, sys: 0 ns, total: 38.7 ms
Wall time: 36.8 ms


In [ ]:
print("Fraction of points outside: ", outside_points/npoints)

Fraction of points outside:  0.214433


In [ ]:
%%time
outside_points = np.sum(np.sqrt(np.sum(points * points, axis = 1)) > 1) # one line code

CPU times: user 34.5 ms, sys: 18.5 ms, total: 53 ms
Wall time: 58.9 ms


In [ ]:
def outside_points_fig(npoints, ndim):
  points = np.random.rand(npoints, ndim);
  return np.sum(np.sqrt(np.sum(points*points, axis = 1)) > 1)/npoints

In [ ]:
outside_points_fig(100000, 2)

0.21548

In [ ]:
for i in range(2, 11):
  print(i, outside_points_fig(100000, i)) # i => ndim

2 0.21137
3 0.4719
4 0.69178
5 0.83553
6 0.91914
7 0.96291
8 0.98357
9 0.99333
10 0.99766


#BroadCasting

In [ ]:
arr1 = np.arange(6)

In [ ]:
arr1 = arr1.reshape((3,2))
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr2 = np.arange(6).reshape((3,2))
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
print(arr1 + arr2)

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [ ]:
arr2[0].reshape((1,2))

array([[0, 1]])

In [ ]:
# arr2[0] is 1*2 and arr1 is 3*2.. hence arr2[0] will be broadcasted to a shape 3*2 and the values gets replicated along the 0th(changed) dim
arr1 + arr2[0].reshape((1,2)) 

array([[0, 2],
       [2, 4],
       [4, 6]])

In [ ]:
arr1 = np.arange(24)
arr1 = arr1.reshape((2,3,4))
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr2 = np.ones((1,4))
arr2

array([[1., 1., 1., 1.]])

In [ ]:
arr1 + arr2 # (2,3,4) + (1,4) => (1,4) broadcasted to (2,3,4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [ ]:
arr1 = np.arange(4)
arr2 = np.arange(5)
print(arr1.shape, arr2.shape)

(4,) (5,)


In [ ]:
#arr1 + arr2 # will throw an error .. as these shapes cannot be mapped and broadcasted

In [ ]:
arr1.reshape((4,1)) + arr2 # (4,1) + (1,5) => both arrays gets braodcasted to (4,5) and gets replicatec accordingly

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

#File Handling

In [ ]:
"""
    Remember that numpy can only read numerical data and not string data .. and as our files planet_small row1 as the name of planets 
    and col1 as the attributes(size, diamater).. numpy do not read such data .. hence it will throw an error
"""

'\n    Remember that numpy can only read numerical data and not string data .. and as our files planet_small row1 as the name of planets \n    and col1 as the attributes(size, diamater).. numpy do not read such data .. hence it will throw an error\n'

In [ ]:
planet_small = np.loadtxt("planets_small-200320-181217.txt") 

ValueError: ignored

In [ ]:
planet_small = np.loadtxt("planets_small-200320-181217.txt", skiprows=1) # skip the 1st row containing names of planets 

ValueError: ignored

In [ ]:
planet_small = np.loadtxt("planets_small-200320-181217.txt", 
                          skiprows=1, usecols=(1,2,3,4,5,6,7,8,9)) # use only those coloumn having numerical data in them 

In [ ]:
planet_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [ ]:
planet_small.shape

(3, 9)

In [ ]:
# planet nig => file contain some unknown values which numpy is taking as string.. hence we have to handle that also.
planets = np.loadtxt("planets-200320-181217.txt", 
                          skiprows=1, usecols=(1,2,3,4,5,6,7,8,9)) 

ValueError: ignored

In [ ]:
# we will use genfromtxt function instead of loadtxt.. genearte from txt
planets = np.genfromtxt("planets-200320-181217.txt", skip_header=1, usecols=(1,2,3,4,5,6,7,8,9))

In [ ]:
planets # unknown will be read as nan (not a number)

In [ ]:
planets.shape

(20, 9)

In [ ]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [ ]:
# replace nan with -1 .. to word with numpy convert nan into some numeriacal value 
planet_new = np.nan_to_num(planets, nan=-1) # nan to numerical

In [ ]:
#Now save these files on cloud so that numpy can use it after word
np.savetxt("planets_new.txt", planet_new, delimiter=',')

In [ ]:
#Now save these files on cloud so that numpy can use it after word
np.save("planets_new", planet_new) # no extension .. as numpy will add its own extension

In [ ]:
!ls -lh # linux cmds to see all the saved available files

total 24K
-rw-r--r-- 1 root root 1.5K Jul 29 06:00 planets-200320-181217.txt
-rw-r--r-- 1 root root 1.6K Jul 29 06:19 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jul 29 06:20 planets_new.txt
-rw-r--r-- 1 root root  254 Jul 29 06:00 planets_small-200320-181217.txt
drwxr-xr-x 1 root root 4.0K Jul 16 13:20 sample_data


In [ ]:
#saving multiple arrays 
arr1 = np.random.rand(1000, 10)
arr2 = np.random.rand(2000, 5)
arr3 = np.random.rand(20, 10000)

In [ ]:
np.savez("many_arrs", arr1, arr2, arr3)

In [ ]:
!ls -lh

total 1.8M
-rw-r--r-- 1 root root 1.7M Jul 29 06:24 many_arrs.npz
-rw-r--r-- 1 root root 1.5K Jul 29 06:00 planets-200320-181217.txt
-rw-r--r-- 1 root root 1.6K Jul 29 06:19 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jul 29 06:20 planets_new.txt
-rw-r--r-- 1 root root  254 Jul 29 06:00 planets_small-200320-181217.txt
drwxr-xr-x 1 root root 4.0K Jul 16 13:20 sample_data


In [ ]:
# load or get the file
arrs = np.load("many_arrs.npz")

In [ ]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [ ]:
arrs["arr_0"].shape

(1000, 10)

In [ ]:
arrs["arr_1"].shape

(2000, 5)

In [ ]:
arrs["arr_2"].shape

(20, 10000)

In [ ]:
# save files as a compressed version
np.savez_compressed("many_files_compressed", arr1, arr2, arr3)

In [ ]:
!ls -lh

total 3.3M
-rw-r--r-- 1 root root 1.7M Jul 29 06:24 many_arrs.npz
-rw-r--r-- 1 root root 1.6M Jul 29 06:27 many_files_compressed.npz
-rw-r--r-- 1 root root 1.5K Jul 29 06:00 planets-200320-181217.txt
-rw-r--r-- 1 root root 1.6K Jul 29 06:19 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jul 29 06:20 planets_new.txt
-rw-r--r-- 1 root root  254 Jul 29 06:00 planets_small-200320-181217.txt
drwxr-xr-x 1 root root 4.0K Jul 16 13:20 sample_data


In [ ]:
arr1 = np.ones((1000, 1000))

In [ ]:
np.savez("zeros_file", arr1)

In [ ]:
np.savez_compressed("zeros_file_compressed", arr1) # numpy will compress the sparsely populated files or more same values files in very efficeint manner 

In [ ]:
!ls -lh

total 11M
-rw-r--r-- 1 root root 1.7M Jul 29 06:24 many_arrs.npz
-rw-r--r-- 1 root root 1.6M Jul 29 06:27 many_files_compressed.npz
-rw-r--r-- 1 root root 1.5K Jul 29 06:00 planets-200320-181217.txt
-rw-r--r-- 1 root root 1.6K Jul 29 06:19 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jul 29 06:20 planets_new.txt
-rw-r--r-- 1 root root  254 Jul 29 06:00 planets_small-200320-181217.txt
drwxr-xr-x 1 root root 4.0K Jul 16 13:20 sample_data
-rw-r--r-- 1 root root  12K Jul 29 06:30 zeros_file_compressed.npz
-rw-r--r-- 1 root root 7.7M Jul 29 06:30 zeros_file.npz
